### ISSUE TITLE
Feature request: sequences

### ISSUE THREAD

**Issue by nat-418** [wez/evremap#12]
It would be good to add a ``[[sequence]]`` type of binding where rather than chords of keys (eg. `KEY_LEFTCTRL` and `KEY_F24`) being pressed at once, sequences of keys pressed one after the other (eg. `KEY_LEFTCTRL` and then `KEY_F24`) can be used as valid values for `input` or `output`.  This would allow both for the recording of simple macros as well as for more (the number of possible mappings is vastly increased) and ergonomically improved (no Emacs pinky) key mappings.

I don't know Rust, but I will try and take time to see if I can hack this together. Might be better implemented as a non-hack, however.

**Comment by wez** [comment]
I've been avoiding complexity because of the running as root requirement, but with that unblocked, I think it's reasonable to expand the functionality.

I would welcome a PR! I don't have much time to work directly on evremap at the moment, but I can spare time to review and make suggestions!
