### ISSUE TITLE
key substitution maps alian keys

### ISSUE THREAD

**Issue by xpseudonym** [wez/evremap#19]
I couldn't think of a better description...

I'm using a HP Spectre laptop with a UK keyboard in the UK.

When I load this:
```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
### capslock = overload(control, esc)

# Remaps the escape key to capslock
### esc = capslock


rightcontrol =  \

### |\
```
I get '`#`' for [`rightcontrol`] and '`~`' for [`shift+rightcontrol`].
I get some other weirdness - like '`£`' for [`#`].

The keyboard is essentially this:
![Screenshot from 2022-09-29 19-24-18](https://user-images.githubusercontent.com/5032475/193112848-355e0e8e-d32a-4562-b654-96dc49916aa9.png)
Except, there's no [`\ & |`] key immediately to the right of the [`leftshift`] key.
I figured for a moment that there was some mismatch between US and UK keyboards because the US [`\ & |`] key is where the UK [`# & ~`] key is - but, when I substituted in the '`#`' instead of '`\`' I got the '`£`' which seems to debunk that theory.

Obviously, I'm trying to map the missing [`\ & |`] key to the [`rightcontrol`] key - which is what is actually written on the [`rightcontrol`] key on my keyboard.

**Comment by wez** [comment]
Did you mean to file this against a different piece of software? I don't understand what you've posted and it doesn't look like evremap configuration

**Comment by xpseudonym** [comment]
Hmm, I think you might be right...
`evermap` is not `keyd` - right?
I'd done such a lot of lovely formatting above...  I wonder if I can just copy & paste into `keyd`'s issues

**Comment by xpseudonym** [comment]
Yes, it does seem I can just copy & paste an issue from one project to another...
See here:
https://github.com/rvaiya/keyd/issues/348#issue-1392265522
