### ISSUE TITLE
cant remap CAPSLOCK to FN 

### ISSUE THREAD

**Issue by luccahuguet** [wez/evremap#26]
this is my current config

```device_name = "BT5.0 KB Keyboard"
phys = "5c:c9:d3:7d:6d:0f"

[[remap]]
input = ["KEY_CAPSLOCK"]
output = ["KEY_FN"]
```

i need FN combinations for several commands such as `fn + } = END`, which is how my keyb works, 
but the remap as it is only removes the capslock function of the capslock key, without adding the fn funcion

have you got an idea of what could be the problem?

**Comment by wez** [comment]
I'd suggest starting evremap with `EVREMAP_LOG=trace` set in the environment to trace the events that are generated when you press keys and verify what events happen when you use the Fn key and also the Fn key combinations you're interested in, and then use that as the basis of your remapping configuration.

**Comment by luccahuguet** [comment]
will try that, thank you

**Comment by wez** [comment]
FWIW, you can now use `evremap debug-events --phys 5c:c9:d3:7d:6d:0f` in `main` for a slightly more convenient way to debug key presses.

**Comment by luccahuguet** [comment]
> FWIW, you can now use `evremap debug-events --phys 5c:c9:d3:7d:6d:0f` in `main` for a slightly more convenient way to debug key presses.

cool, ty for the info
