### ISSUE TITLE
works in tty, but not in compositor.

### ISSUE THREAD

**Issue by dmxk06** [wez/evremap#28]
when i remap a key event on my touch pen, it works in the tty, but doesnt seem to work in a wayland compositor(i tried hyprland and sway). it is still registered by evtest and wev as the right key event, but applications seem to ignore it.

**Comment by dmxk06** [comment]
ok, so apparently different programs report different input events for the same action. some report BTN_STYLUS and some report TABLET_TOOL_BUTTON. since the first only works in the tty and i can't remap the second using this, i'm not sure what to do

**Comment by dmxk06** [comment]
if run with the EVREMAP_LOG=trace envvar, it also display the right key event both for input and output.

**Comment by wez** [comment]
Sounds like an issue outside the scope of evremap, sorry!
