### ISSUE TITLE
No way to access keys absent from keyboard

### ISSUE THREAD

**Issue by nileoe** [wez/evremap#34]
I'm using a keyboard with a UK physical layout, but I'm using another (Swiss) layout. The physical key for 'baskslash' doesn't exist on my keyboard (as with my Swiss layout, the resuling key is mapped to the $ sign). I wanted to use evremap to regain access to the backslash symbol by mapping an unused key to it.
I tried mapping an unused key to KEY_BACKSLASH, but that actually maps the key to the $ sign. I also can't find the angle brackets (less/grater than) in the evremap list-keys command, I suspect that is because they're located on the same key as where by backslash would be, and so I can't access them. Am I right to assume I can't get what I want with evremap?

**Comment by wez** [comment]
evremap operates on evdev keyboard events which are at a lower layer than your window environment keyboard layout processing.  I suspect that you'll need to find another way to express this sort of remapping for your situation, sorry!
