### ISSUE TITLE
Not working properly in Sway + XKB

### ISSUE THREAD

**Issue by kohpai** [wez/evremap#43]
Hi,

I am using Sway and XKB to switch between my keyboard layouts (TH and US).
This had been working out of the box since I installed Sway on my laptop until I ran evremap.

This is the XKB configuration part of my Sway configuration:

```
input "1:1:AT_Translated_Set_2_keyboard" {
    xkb_layout us,th
    xkb_model pc105
    xkb_options grp:alt_space_toggle
}
```

As you can see, Alt+Space is supposed to change my keyboard layout.

And here is my evremap config (*whole file*):

```
device_name = "AT Translated Set 2 keyboard"

[[dual_role]]
input = "KEY_SYSRQ"
hold = ["KEY_RIGHTMETA"]
tap = ["KEY_PRINT"]
```

The remap works. But whenever I start `evremap.service`, the xkb toggle stops working.
The toggle starts working again if I stop `evremap.service`.
I thought this was a common problem, but after searching in Issues, I don't see others similar to this.

I would appreciate any helps, thank you very much!

**Comment by kohpai** [comment]
**Update:** I have moved away from Sway to Hyprland just a moment ago, and want to give an update on this issue. Both evremap and XKB WORKS on Hyprland.

**Comment by wez** [comment]
I suspect that the sway config isn't correctly targeting the remapped device so its config isn't being applied. This isn't an evremap issue.
