### ISSUE TITLE
hoping to add copilot key support, or indirectly, remap using key code

### ISSUE THREAD

**Issue by YjzJim** [wez/evremap#50]

**Comment by YjzJim** [comment]
copilot key is KEY_LEFTSHIFT + KEY_LEFTMETA

**Comment by YaQia** [comment]
> copilot key is KEY_LEFTSHIFT + KEY_LEFTMETA

Hi there, could you tell me how do you remap it into `KEY_RIGHTCTRL`? Because in my case, copilot key emits a key combo (scancode: db 2a 6e 6e 2a db) and never can hold the key press (even with the key held).

**Comment by YjzJim** [comment]
This works: @YaQia 
[[remap]]
input = ["KEY_LEFTMETA", "KEY_LEFTSHIFT"]
output = ["KEY_RIGHTCTRL"]

My problem was and still is that it also compromises the original key combo which i may need for my wm.
