### ISSUE TITLE
Please publish on crates.io

### ISSUE THREAD

**Issue by koutheir** [wez/evremap#63]
Given that this program was useful enough for me, I think more people would discover it and have access to it, if it is published on [`crates.io`](https://crates.io). This would allow installing simply by typing `cargo install evremap`.

**Comment by koutheir** [comment]
FYI, the way I found this program was through [ArchWiki](https://wiki.archlinux.org/title/Input_remap_utilities).

**Comment by wez** [comment]
FWIW, I don't really consider `cargo install` to be a good fit for installing a service that should really have a corresponding systemd/init/service configuration. Deploying those sorts of things requires a native system package which is something that you can reconcile for yourself if you have checked out the repo. `cargo install` doesn't make those service configuration files available, so while it may make one aspect of setting up `evremap` slightly more convenient, it also reduces convenience.

You might argue that it is slightly better than not having any prescribed packing here in the repo, but it's not really: it will generate questions and support burden from folks that assume that it will properly take care of setting things up, and correctly uninstalling things later, and `cargo install` has no provisions for that sort of thing.

I'm open to seeing some changes here in the CI to build binaries, debs and rpms and so on, but I currently do not have bandwidth for that.

**Comment by koutheir** [comment]
I agree. It can confuse people to run an `install` command that doesn't perform a proper installation. It would be more helpful to make proper packages for different distributions, or maybe a flatpack.
