### ISSUE TITLE
Invalid key KEY_DASHBOARD from Akko Keyboard

### ISSUE THREAD

**Issue by jantolentino** [wez/evremap#71]
Hi,

I got this error while trying to remap `KEY_DASHBOARD` to `KEY_F4`.

```
    1: TOML parse error at line 16, column 9
          |
       16 | input = ["KEY_DASHBOARD"]
          |         ^^^^^^^^^^^^^^^^^
       Invalid key `KEY_DASHBOARD`.  Use `evremap list-keys` to see possible keys.
```

I'm using `evtest` to scan for key codes. And did register as `KEY_DASHBOARD`.

```
Event: time 1722005849.265832, -------------- SYN_REPORT ------------
Event: time 1722005849.323791, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7003d
Event: time 1722005849.323791, type 1 (EV_KEY), code 204 (KEY_DASHBOARD), value 0
Event: time 1722005849.323791, -------------- SYN_REPORT ------------
Event: time 1722005849.653820, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7003d
Event: time 1722005849.653820, type 1 (EV_KEY), code 204 (KEY_DASHBOARD), value 1
```

Can this be added to the list of possible keys?

**Comment by wez** [comment]
Unsure. Maybe there's a different version of the underlying evdev stuff?
In the meantime, try using the `evremap debug-events` command to see how your key shows up: https://github.com/wez/evremap/commit/d31226fe69908f6c03260cc3c10fe9d3fce283f1

**Comment by jantolentino** [comment]
Indeed! It was printing `KEY_ALL_APPLICATIONS` on `evremap debug-events`. It works perfectly now. Thanks!
